---
  - name: dhruv_application_deployment
    hosts: node2
    remote_user: admin
    become: true
    tasks:
      - name: Install Firewalld, Mariadb, Httpd, php & python3
        yum:
          name:
            - firewalld
            - mariadb-server
            - httpd
            - php
            - php-mysqlnd
            - python3
            - git
            - vim
          state: present

      - name: Enable FirewallD, httpd & Mariadb
        service:
          name: "{{ item }}"
          state: started
          enabled: yes
        loop:
          - firewalld
          - httpd
          - mariadb

      - name: Open ports for HTTPD & Mariadb
        firewalld:
          port: "{{ item }}"
          permanent: yes
          zone: public
          state: enabled
        loop:
          - 80/tcp
          - 3306/tcp

      - name: Reload FirewallD Service
        systemd:
         name: firewalld
         state: reloaded

      - name: Install pip mysql module
        pip:
          name: pymysql

      - name: Create Database
        mysql_db:
          name: ecomdb
          state: import
          target: /tmp/db-load-script.sql

      - name: Add user to database
        mysql_user:
          name: ecomdb
          host: localhost
          priv: 'ecomdb.*:ALL'
          password: ecompassword
          state: present

      - name: Clone the repo
        git:
          repo: 'https://github.com/kodekloudhub/learning-app-ecommerce.git'
          dest: /var/www/html

      - name: Search and Replace
        replace:
          path: /var/www/html/index.php
          regexp: '172.20.1.101'
          replace: 'localhost'
          backup: yes
